# Generated by Django 4.1.7 on 2023-03-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.CharField(max_length=50)),
                ('stars', models.IntegerField(max_length=20)),
            ],
        ),
    ]
