# Generated by Django 4.1.7 on 2023-03-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_rating',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
