# Generated by Django 4.1.7 on 2023-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_global_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_rating',
            name='stars',
            field=models.CharField(max_length=10),
        ),
    ]
