# Generated by Django 4.1.7 on 2023-03-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_global_rating_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_rating',
            name='whole_item',
            field=models.JSONField(default={}),
        ),
    ]
