# Generated by Django 4.1.7 on 2023-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_global_rating_whole_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounds', models.JSONField()),
            ],
        ),
    ]
